trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.9'
  functionAppNameProd: 'prodbestrongfuncapp1'
  functionAppNameDev: 'devbestrongfuncapp1'
  resourceGroupProd: 'rg-prod'
  resourceGroupDev: 'rg-dev'

stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: BuildJob
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: |
        mkdir -p $(Build.ArtifactStagingDirectory)/function_package
        cp -r PdfOcrFunction $(Build.ArtifactStagingDirectory)/function_package/
        cp host.json requirements.txt $(Build.ArtifactStagingDirectory)/function_package/
      displayName: 'Prepare Function Package'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/function_package'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/function-app.zip'
        replaceExistingArchive: true

    - publish: '$(Build.ArtifactStagingDirectory)/function-app.zip'
      artifact: function-package

- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: Build
  jobs:
  - deployment: DeployJob
    environment: $(Build.SourceBranchName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'bestrong-arm'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                if [ "$(Build.SourceBranch)" = "refs/heads/main" ]; then
                  APP_NAME=$(functionAppNameProd)
                  RG_NAME=$(resourceGroupProd)
                else
                  APP_NAME=$(functionAppNameDev)
                  RG_NAME=$(resourceGroupDev)
                fi

                echo "Deploying to Function App: $APP_NAME"

                az functionapp config set \
                  --name $APP_NAME \
                  --resource-group $RG_NAME \
                  --linux-fx-version "Python|3.9"

          - task: AzureFunctionApp@1
            inputs:
              azureSubscription: 'bestrong-arm'
              appType: 'functionAppLinux'
              appName: '$(if $(Build.SourceBranch) == refs/heads/main) $(functionAppNameProd) $(functionAppNameDev)'
              package: '$(Pipeline.Workspace)/function-package/function-app.zip'
              deploymentMethod: 'auto'
              appSettings: '-FUNCTIONS_WORKER_RUNTIME python -FUNCTIONS_EXTENSION_VERSION ~4 -FileShareConnectionString "$(FileShareConnectionString)" -FormRecognizerEndpoint "$(FormRecognizerEndpoint)" -FormRecognizerKey "$(FormRecognizerKey)" -BlobStorageConnectionString "$(BlobStorageConnectionString)" -DiscordWebhookUrl "$(DiscordWebhookUrl)" -SlackWebhookUrl "$(SlackWebhookUrl)"'

          - script: |
              echo "Notifying deployment success."
              curl -X POST -H 'Content-type: application/json' \
                --data "{\"content\":\"Deployment completed: $(Build.SourceBranchName)\"}" \
                "$(DiscordWebhookUrl)"

              curl -X POST -H 'Content-type: application/json' \
                --data "{\"text\":\"Deployment completed: $(Build.SourceBranchName)\"}" \
                "$(SlackWebhookUrl)"
            condition: always()